display_name: RetroPod
icon: snap/gui/retropod.png

keywords:
  - Music
  - Audio
  - iPod
  - Local
  - Songs
  - Offline

generic_name: Local Music Player
categories:
  - Music

startup_notify: true